// Simple static AI summary logic
export function generateAISummary(text: string): string {
  // Take first 2 sentences as summary (static logic)
  if (!text) return '';
  const sentences = text.match(/[^.!?]+[.!?]+/g) || [];
  return sentences.slice(0, 2).join(' ').trim();
}

// Simple English to Urdu dictionary
const englishToUrdu: Record<string, string> = {
  // Expanded dictionary
  i: 'میں',
  you: 'آپ',
  he: 'وہ',
  she: 'وہ',
  we: 'ہم',
  they: 'وہ لوگ',
  my: 'میرا',
  your: 'آپ کا',
  his: 'اس کا',
  her: 'اس کی',
  our: 'ہمارا',
  their: 'ان کا',
  name: 'نام',
  book: 'کتاب',
  school: 'سکول',
  teacher: 'استاد',
  student: 'طالب علم',
  city: 'شہر',
  country: 'ملک',
  home: 'گھر',
  house: 'مکان',
  street: 'گلی',
  road: 'سڑک',
  car: 'گاڑی',
  bus: 'بس',
  train: 'ٹرین',
  airplane: 'جہاز',
  water: 'پانی',
  food: 'کھانا',
  fruit: 'پھل',
  vegetable: 'سبزی',
  animal: 'جانور',
  bird: 'پرندہ',
  tree: 'درخت',
  flower: 'پھول',
  sun: 'سورج',
  moon: 'چاند',
  star: 'ستارہ',
  sky: 'آسمان',
  earth: 'زمین',
  air: 'ہوا',
  fire: 'آگ',
  rain: 'بارش',
  wind: 'ہوا',
  morning: 'صبح',
  evening: 'شام',
  night: 'رات',
  week: 'ہفتہ',
  month: 'مہینہ',
  year: 'سال',
  today: 'آج',
  yesterday: 'کل',
  tomorrow: 'کل',
  father: 'والد',
  mother: 'والدہ',
  brother: 'بھائی',
  sister: 'بہن',
  son: 'بیٹا',
  daughter: 'بیٹی',
  friend: 'دوست',
  family: 'خاندان',
  work: 'کام',
  job: 'نوکری',
  money: 'پیسہ',
  market: 'بازار',
  shop: 'دکان',
  hospital: 'ہسپتال',
  doctor: 'ڈاکٹر',
  nurse: 'نرس',
  police: 'پولیس',
  fireman: 'فائر مین',
  teacher: 'استاد',
  student: 'طالب علم',
  computer: 'کمپیوٹر',
  phone: 'فون',
  internet: 'انٹرنیٹ',
  email: 'ای میل',
  message: 'پیغام',
  news: 'خبریں',
  newspaper: 'اخبار',
  television: 'ٹیلی ویژن',
  radio: 'ریڈیو',
  music: 'موسیقی',
  movie: 'فلم',
  game: 'کھیل',
  sport: 'کھیل',
  cricket: 'کرکٹ',
  football: 'فٹ بال',
  hockey: 'ہاکی',
  tennis: 'ٹینس',
  run: 'دوڑنا',
  walk: 'چلنا',
  jump: 'چھلانگ',
  sit: 'بیٹھنا',
  stand: 'کھڑا ہونا',
  sleep: 'سونا',
  eat: 'کھانا',
  drink: 'پینا',
  read: 'پڑھنا',
  write: 'لکھنا',
  listen: 'سننا',
  speak: 'بولنا',
  hear: 'سننا',
  see: 'دیکھنا',
  look: 'دیکھنا',
  watch: 'دیکھنا',
  smile: 'مسکرانا',
  cry: 'رونا',
  laugh: 'ہنسنا',
  love: 'محبت',
  hate: 'نفرت',
  happy: 'خوش',
  sad: 'اداس',
  angry: 'غصہ',
  afraid: 'ڈرا ہوا',
  strong: 'مضبوط',
  weak: 'کمزور',
  big: 'بڑا',
  small: 'چھوٹا',
  long: 'لمبا',
  short: 'چھوٹا',
  tall: 'لمبا',
  high: 'اونچا',
  low: 'نیچا',
  hot: 'گرم',
  cold: 'سرد',
  clean: 'صاف',
  dirty: 'گندا',
  beautiful: 'خوبصورت',
  ugly: 'بدصورت',
  easy: 'آسان',
  difficult: 'مشکل',
  fast: 'تیز',
  slow: 'آہستہ',
  new: 'نیا',
  old: 'پرانا',
  good: 'اچھا',
  bad: 'برا',
  the: 'دی',
  and: 'اور',
  is: 'ہے',
  blog: 'بلاگ',
  post: 'تحریر',
  content: 'مواد',
  summary: 'خلاصہ',
  you: 'آپ',
  we: 'ہم',
  are: 'ہیں',
  this: 'یہ',
  that: 'وہ',
  for: 'کے لئے',
  with: 'کے ساتھ',
  on: 'پر',
  in: 'میں',
  to: 'کو',
  from: 'سے',
  by: 'بذریعہ',
  of: 'کا',
  a: 'ایک',
  an: 'ایک',
  it: 'یہ',
  as: 'جیسے',
  at: 'پر',
  was: 'تھا',
  were: 'تھے',
  be: 'ہونا',
  have: 'ہے',
  has: 'ہے',
  not: 'نہیں',
  can: 'سکتا ہے',
  will: 'ہوگا',
  do: 'کرو',
  did: 'کیا',
  about: 'کے بارے میں',
  new: 'نیا',
  old: 'پرانا',
  good: 'اچھا',
  bad: 'برا',
  day: 'دن',
  time: 'وقت',
  people: 'لوگ',
  work: 'کام',
  use: 'استعمال',
  make: 'بنائیں',
  get: 'حاصل کریں',
  like: 'پسند',
  help: 'مدد',
  learn: 'سیکھیں',
  read: 'پڑھیں',
  write: 'لکھیں',
  see: 'دیکھیں',
  go: 'جائیں',
  come: 'آئیں',
  know: 'جانیں',
  think: 'سوچیں',
  find: 'تلاش کریں',
  give: 'دیں',
  tell: 'بتائیں',
  want: 'چاہتے ہیں',
  need: 'ضرورت',
  feel: 'محسوس کریں',
  show: 'دکھائیں',
  call: 'کال کریں',
  try: 'کوشش کریں',
  ask: 'پوچھیں',
  move: 'حرکت کریں',
  play: 'کھیلیں',
  run: 'دوڑیں',
  walk: 'چلیں',
  eat: 'کھائیں',
  drink: 'پیئیں',
  sleep: 'سوئیں',
  start: 'شروع کریں',
  end: 'ختم کریں',
  open: 'کھولیں',
  close: 'بند کریں',
  live: 'رہیں',
  die: 'مرنا',
  love: 'محبت',
  hate: 'نفرت',
  win: 'جیتیں',
  lose: 'ہاریں',
  buy: 'خریدیں',
  sell: 'بیچیں',
  send: 'بھیجیں',
  receive: 'حاصل کریں',
  build: 'بنائیں',
  break: 'توڑیں',
  choose: 'منتخب کریں',
  change: 'تبدیل کریں',
  watch: 'دیکھیں',
  listen: 'سنیں',
  speak: 'بولیں',
  hear: 'سنیں',
  smile: 'مسکرائیں',
  cry: 'روئیں',
  hope: 'امید',
  dream: 'خواب',
  plan: 'منصوبہ',
  study: 'مطالعہ',
  teach: 'سکھائیں',
  // ...add more words as needed
};

export function translateToUrdu(text: string): string {
  if (!text) return '';
  return text
    .split(' ')
    .map(word => englishToUrdu[word.toLowerCase()] || word)
    .join(' ');
}
